xa=input("请输入矩阵第一行的第一个元素：")
xb=input("请输入矩阵第一行的第二个元素：")
xc=input("请输入矩阵第一行的第三个元素：")
x=[]
x.append(int(xa))
x.append(int(xb))
x.append(int(xc))
ya=input("请输入矩阵第二行的第一个元素：")
yb=input("请输入矩阵第二行的第二个元素：")
yc=input("请输入矩阵第二行的第三个元素：")
y=[]
y.append(int(ya))
y.append(int(yb))
y.append(int(yc))
za=input("请输入矩阵第三行的第一个元素：")
zb=input("请输入矩阵第三行的第二个元素：")
zc=input("请输入矩阵第三行的第三个元素：")
z=[]
z.append(int(za))
z.append(int(zb))
z.append(int(zc))
q=x[0]+y[1]+z[2]
w=x[2]+y[1]+z[0]
print("左对角线的和为%d"%q)
print("右对角线的和为%d"%w)
