sxa=eval(input("请输入第一个矩阵第一行的第一个元素："))
sxb=eval(input("请输入第一个矩阵第一行的第二个元素："))
sxc=eval(input("请输入第一个矩阵第一行的第三个元素："))
sya=eval(input("请输入第一个矩阵第二行的第一个元素："))
syb=eval(input("请输入第一个矩阵第二行的第二个元素："))
syc=eval(input("请输入第一个矩阵第二行的第三个元素："))
sza=eval(input("请输入第一个矩阵第三行的第一个元素："))
szb=eval(input("请输入第一个矩阵第三行的第二个元素："))
szc=eval(input("请输入第一个矩阵第三行的第三个元素："))
txa=eval(input("请输入第二个矩阵第一行的第一个元素："))
txb=eval(input("请输入第二个矩阵第一行的第二个元素："))
txc=eval(input("请输入第二个矩阵第一行的第三个元素："))
tya=eval(input("请输入第二个矩阵第二行的第一个元素："))
tyb=eval(input("请输入第二个矩阵第二行的第二个元素："))
tyc=eval(input("请输入第二个矩阵第二行的第三个元素："))
tza=eval(input("请输入第二个矩阵第三行的第一个元素："))
tzb=eval(input("请输入第二个矩阵第三行的第二个元素："))
tzc=eval(input("请输入第二个矩阵第三行的第三个元素："))
a=sxa+txa
b=sxb+txb
c=sxc+txc
d=sya+tya
e=syb+tyb
f=syc+tyc
g=sza+tza
h=szb+tzb
i=szc+tzc
print(a,end=" ")
print(b,end=" ")
print(c,end=" \n")
print(d,end=" ")
print(e,end=" ")
print(f,end=" \n")
print(g,end=" ")
print(h,end=" ")
print(i,end=" ")

